### ISSUE TITLE
Where are the pre-built binaries?

### ISSUE THREAD

**Issue by bichonnages** [K-Visscher/pro-intellimouse-control-panel#11]
I am sorry -- a little bit lost here.
Where are the pre-built binaries?
Thanks!

**Comment by K-Visscher** [comment]
Sorry for my late response.

There aren't any, I intended on making them but I felt it was too much of hassle to setup all the various OS'es and automate the releases using CI/CD pipelines such as GitHub actions.
If anyone would be willing to make a pull-request with GitHub actions that perform the building process that would be great.

Does this answer your question?

**Comment by K-Visscher** [comment]
I've just updated the README.md so that it isn't lying anymore =^.^=

**Comment by bountycortez** [comment]
yes and thanks for the program. love my intellimouse and are happy that i can use and adjust it due to your program.
bernd
